# Generated by Django 4.2.6 on 2023-11-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=200)),
                ('result_code', models.CharField(max_length=100)),
            ],
        ),
    ]
